---
train:
  params:
    batch_size: 256
    epoch: 20
    lr: 0.001
    decay: 0.1
    decay_step: 75000
    loss: MSELoss
  save:
    save_path: "/path/to/save/directory"
    model_name: Gazetracker
    step: 5
  data:
    image: "/path/to/image/directory"
    label: "/path/to/label/train/directory"
  pretrains: "None"
test:
   load:
      begin_step: 5
      end_step: 20
      steps: 5
      load_path: "/path/to/load/directory"
      model_name: Itracker
   data:
      image: "/path/to/image/directory"
      label: "/path/to/label/test/directory"
reader: reader_gc